### ISSUE TITLE
The operation couldn’t be completed.(com.twilio.video error 0) issue while connecting to VideoRoom

### ISSUE THREAD

**Issue by pranita88pawar** [jonedavis/TwilioXamarinRoomsSampleIOS#1]
Hi,

I am trying to run this sample , i have generated token by using startup given on this link :https://github.com/TwilioDevEd/video-quickstart-csharp(with all secret and apikeys of my Twilio account).

Its throwing me 'The operation couldn’t be completed.(com.twilio.video error 0)' while connecting to entered room , Could you please help on this? I am stuck on this issue from last 4-5 days. 

Thanks and Regards,
Pranita Pawar.

**Comment by jonedavis** [comment]
@pranita88pawar Are you running this on a device or simulator? This demo won't work on a simulator. Can you provide me with additional information that will help troubleshoot this?

**Comment by pranita88pawar** [comment]
@jonedavis  Yes i have tried it on device both iPhone and iPad also.

Below steps i have followed to run this application:
1. I have configured video quick start project to get token with my account $twilioAccountSid, $twilioApiKey, $twilioApiSecret ,$twilioVideoConfigurationSID.

2.I published this project on Azure, so that i can refer it in xamarin project to get token.
3. I replaced token URL with my URL, deployed project on device.
4.It got deployed successfully on device, i entered roomname as 'MyRoom' and pressed connect button.
5. It goes fine till room object is created , but after that it takes some time and directly throws The operation couldn’t be completed.(com.twilio.video error 0) exception.

for the token generated please find below image attached :

![d6291428-029c-11e7-8400-69feb2328b53](https://cloud.githubusercontent.com/assets/6493869/23642779/4d777d40-0323-11e7-944f-497778f3cb9b.png)


Thanks !

**Comment by jonedavis** [comment]
@pranita88pawar Do you have a stack trace you can send over?
I'll try to reproduce this this weekend.

**Comment by pranita88pawar** [comment]
@jonedavis  I tried it yesterday, problem is solved and i come to know this was due to wrongly generated
token, now i am able to run it successfully.

Thanks for Help !!!!
